extension=/home/gani/.local/lib/php/modules/pdo_sqlite.so
extension=/home/gani/.local/lib/php/modules/sqlite3.so
extension=/usr/lib/php/modules/pdo_mysql.so
extension=/usr/lib/php/modules/mysqli.so
extension=/usr/lib/php/modules/curl.so
extension=/usr/lib/php/modules/zip.so
extension=/usr/lib/php/modules/intl.so
extension=/usr/lib/php/modules/bcmath.so
extension=/usr/lib/php/modules/iconv.so
extension=/usr/lib/php/modules/exif.so
memory_limit = 512M
upload_max_filesize = 20M
post_max_size = 25M
